version: "3"
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/working
    working_dir: /working
    ports:
      - 8888:8888
      - 5000:5000
    environment: 
      - PYTHONPATH=/working
    command: bash -c "jupyter lab --notebook-dir=/working --ip=0.0.0.0 --allow-root --no-browser"